on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: master
            fetch-depth: 10
            submodules: true
            
      - name: Make CSS Directory
        run: mkdir -vp css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.6
        with:
          source: _scss/main.scss
          destination: /home/runner/work/vmcs-7wc-website/vmcs-7wc-website/css/main.css
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
